### ISSUE TITLE
is there an "as is" invocation concept?

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/bioconductor_devel#5]
I am finding that when I use "bioconductor devel"  I may have to wait for
some GB of layers to be retrieved before R will start.  Probably a tag needs to be specified
to select something other than 'latest', to indicate that I am happy to use an
image without updates.

**Comment by lwaldron** [comment]
Sorry about that @vjcitn. I've created tags `waldronlab/bioconductor_devel:stable` and `waldronlab/bioconductor_release:stable` that you can use. I have some significant refactoring to do (including building on @nturaga's https://github.com/Bioconductor/bioconductor_full image) so I'm not sure if this will remain the solution, but in the meantime it'll avoid the frequent downloads.
