### ISSUE TITLE
docker hub builds

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/bioconductor_devel#8]
> BTW Dockerhub is already attempting to build the image (e.g. https://hub.docker.com/repository/registry-1.docker.io/waldronlab/bioconductor_devel/builds/bef69c82-dbe0-4ab4-a892-2262d2a4e684) but it fails with errors like:
> 
> ```
> Starting build of index.docker.io/waldronlab/bioconductor_devel:latest...
> Step 1/7 : ARG VERSION
> Step 2/7 : FROM bioconductor/bioconductor_full:${VERSION}
> invalid reference format
> ```
@lwaldron 
I've looked into this and removed the `ARG` version and related code in the `bioconductor` script following the conclusions above. See #6 

I can fix the setup on `docker hub`. Do you want to (1) create folders for different builds (`RELEASE_3_10`, `devel`) in the repository or (2) use different branches for each of the builds (`RELEASE_3_10`, `master`)? I'm leaning towards the second option because the `Dockerfile` can stay where it is and I don't expect the release version to be modified often.

**Comment by lwaldron** [comment]
I agree about the second option. Thanks Marcel.

**Comment by LiNk-NY** [comment]
We have two successful builds: `RELEASE_3_10` and `devel` 
See: https://hub.docker.com/repository/docker/waldronlab/bioconductor_devel/builds
